# Category.create(name: 'autos')
# Category.create(name: 'pets')
# Category.create(name: 'electronics')
# Product.create(title:'Car',description:'Beatiful 1973 car. Its yellow', price: 200, category_id: Category.first.id)
# Product.create(title:'Laptop',description:'Not working Mac computer. Its red', price: 100, category_id: Category.last.id)
# Product.create(title:'iMac',description:'Fine and beatufigul', price: 1100, category_id: Category.last.id)
# Product.create(title:'Dog leash',description:'good dog leash NEver used. Its red', price: 10, category_id: 2)
# Product.create(title:'Screen',description:'I dont need it.', price: 12, category_id: Category.last.id)
# Product.create(title:'Mouse',description:'I only have the mouse not the able. no guarantee', price: 1030, category_id: Category.last.id)
# Product.all.inspect