Product.create(title:'Car',description:'Beatiful 1973 car. Its yellow', price: 200)
Product.create(title:'Laptop',description:'Not working Mac computer. Its red', price: 100)
Product.create(title:'iMac',description:'Fine and beatufigul', price: 1100)
Product.create(title:'Dog leash',description:'good dog leash NEver used. Its red', price: 10)
Product.create(title:'Screen',description:'I dont need it.', price: 12)
Product.create(title:'Mouse',description:'I only have the mouse not the able. no guarantee', price: 1030)